name: Merge Conflict Check

on:
  push:
  pull_request:

permissions:
  pull-requests: write

jobs:
  auto-comment-merge-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: codytseng/auto-comment-merge-conflicts@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-body: "Merge Conflict"
          wait-ms: 3000
          max-retries: 5
